name: Python Connectors CI

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  detect-clients:
    runs-on: ubuntu-latest
    outputs:
      clients: ${{ steps.detect.outputs.clients }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect all clients
        id: detect
        run: |
          ALL_CLIENTS=$(ls -d clients/*/ | xargs -n 1 basename | jq -R -s -c 'split("\n")[:-1]')
          echo "Detected clients: $ALL_CLIENTS"
          echo "clients=$ALL_CLIENTS" >> $GITHUB_ENV
          echo "::set-output name=clients::$ALL_CLIENTS"

  build:
    needs: detect-clients
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client: ${{ fromJson(needs.detect-clients.outputs.clients) }}
        python-version: ["3.12"]
        poetry-version: ["1.8.4"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip && \
          pip3 install ruff black && \
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build ${{ matrix.client }} client
        run: |
          if [ "${{ matrix.client }}" == "common" ]; then
            cd common
          else
            cd clients/${{ matrix.client }}
          fi

          # Install dependencies
          poetry install

          # Format
          poetry run black .

          # Lint
          poetry run ruff check --fix .

          # Test
          poetry run pytest tests

          # Build
          poetry build
